#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XFormsUI.Droid.Resource", IsApplication=true)]

namespace XFormsUI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::XFormsUI.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::XFormsUI.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int entry_border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fblogin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Foody1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Foody10 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Foody11 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Foody12 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Foody13 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Foody2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Foody3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Foody4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Foody5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Foody6 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Foody7 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Foody8 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Foody9 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int iconEmail = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int iconPassword = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int iconUsername = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int rainBus = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
